number1 = int(input("Enter first number: "))
number2 = int(input('Enter second number: '))
number3 = int(input('Enter third number: '))
number4 = int(input('Enter fourth number: '))
number5 = int(input('Enter fifth number: '))
print(number1+number2)
print(number1-number2)
print(number1/number2)
print(number1*number2)
print(number2-number3)
print(number2/number3)
print(number2*number3)
print(number2+number3)
print(number3-number4)
print(number3/number4)
print(number3*number4)
print(number3+number4)
print(number4-number5)
print(number4/number5)
print(number4*number5)
print(number4+number5)
print(number1-number2)
print(number1/number2)
print(number1*number2)
print(number5+number5)