name = "mate"
#name არის ცვლადი
# = არის ცვლადისთვის მიმნიჭებელო სიმბოლო
# "mate" არის ცვლადისთვის მნიშვნელობა

surname = "ghviniashvili"

# print(name)
#პრინტ ფუნქციას გადაეცემა ეკრანზე გამოსატანი ობიექტი 

name = "mate" #ეს არის str (string) ტიპის ცვლადი
age = 11 # ეს არის int ( integer ) მთელი რიცხვი
height = 152  #ეს არის fLoat ტიპის ცვლადი ( ათწილადი )
#booLean (booL) ტიპის ცვლადი 

knows_programming = True #True ან False
is_ugly = False #snakecase( უბრალოდ წერის სტილი სტანდარტულად )

isugly = False # ჯავასკრიპტული camelcase


# print(name + "" + surname)

# #სტრინგი არის ბრჭყალებში მოქცეული სიმბოლოები

# print(name + age)

#print(type(age))
#print(type(name))
#print(type(surname))
#print(type(knows_programming))

print(name + " " + str(age))

# print(name + " " + str(age)) # მე ვარ მათე ღვინიაშვილი 11 წლის 1მ და 52სმ